### ISSUE TITLE
Need URL to POST song deletions to

### ISSUE THREAD

**Issue by cpeter256** [cpeter256/soundstash#8]
There needs to be a url which I can POST a request to delete a song UID from the playlist

**Comment by moonlightdrive** [comment]
Don't have the backend logic for this implemented yet, but send the song's id to `/library/<playlist-name>/delete`

(feel free to come up with a better name than "delete")

But this way it's similar to song addition, which goes to `/library/<playlist>/add`

**Comment by moonlightdrive** [comment]
Actually ignore previous post. Do

```
DELETE /library/<playlist-name>/<song-id>
```
